-- Andrew Imredy api5, Ted Balashov thb46, Christopher Flores cwf24

--INSERT VALUES INTO THE MUTUAL DATE TABLE
INSERT INTO MUTUAL_DATE (p_date)
VALUES (TO_DATE('04-APR-20', 'DD-MON-YY'));


--INSERT VALUES INTO THE CUSTOMER TABLE
INSERT INTO CUSTOMER
VALUES ('mike', 'Mike Costa', 'mike@betterfuture.com', '1st street', 'pwd', 750);
INSERT INTO CUSTOMER
VALUES ('mary', 'Mary Chrysanthis', 'mary@betterfuture.com', '2nd street', 'pwd', 0);

--INSERT VALUES INTO THE ADMINISTRATOR TABLE
INSERT INTO ADMINISTRATOR
VALUES ('admin', 'Administrator', 'admin@betterfuture.com', '5th Ave, Pitt', 'root');

--INSERT VALUES INTO THE MUTUAL FUND TABLE
INSERT INTO MUTUAL_FUND
VALUES ('MM', 'money-market', 'money market, conservative', 'fixed', TO_DATE('06-JAN-20', 'DD-MON-YY'));
INSERT INTO MUTUAL_FUND
VALUES ('RE', 'real-estate', 'real estate', 'fixed', TO_DATE('09-JAN-20', 'DD-MON-YY'));
INSERT INTO MUTUAL_FUND
VALUES ('STB', 'short-term-bonds', 'short term bonds', 'bonds', TO_DATE('10-JAN-20', 'DD-MON-YY'));
INSERT INTO MUTUAL_FUND
VALUES ('LTB', 'long-term-bonds', 'long term bonds', 'bonds', TO_DATE('11-JAN-20', 'DD-MON-YY'));
INSERT INTO MUTUAL_FUND
VALUES ('BBS', 'balance-bonds-stocks', 'balance bonds and stocks', 'mixed', TO_DATE('12-JAN-20', 'DD-MON-YY'));
INSERT INTO MUTUAL_FUND
VALUES ('SRBS', 'social-response-bonds-stocks', 'social responsibility and stocks', 'mixed',
        TO_DATE('12-JAN-20', 'DD-MON-YY'));
INSERT INTO MUTUAL_FUND
VALUES ('GS', 'general-stocks', 'general stocks', 'stocks', TO_DATE('16-JAN-20', 'DD-MON-YY'));
INSERT INTO MUTUAL_FUND
VALUES ('AS', 'aggressive-stocks', 'aggressive stocks', 'stocks', TO_DATE('23-JAN-20', 'DD-MON-YY'));
INSERT INTO MUTUAL_FUND
VALUES ('IMS', 'international-markets-stock', 'international markets stock, risky', 'stocks',
        TO_DATE('30-JAN-20', 'DD-MON-YY'));

--INSERT VALUES INTO THE OWNS TABLE
INSERT INTO OWNS
VALUES ('mike', 'RE', 50);

--INSERT VALUES INTO THE TRXLOG TABLE
INSERT INTO TRXLOG
VALUES (DEFAULT, 'mike', NULL, TO_DATE('29-MAR-20', 'DD-MON-YY'), 'deposit', NULL, NULL, 1000);
INSERT INTO TRXLOG
VALUES (DEFAULT, 'mike', 'MM', TO_DATE('29-MAR-20', 'DD-MON-YY'), 'buy', 50, 10, 500);
INSERT INTO TRXLOG
VALUES (DEFAULT, 'mike', 'RE', TO_DATE('29-MAR-20', 'DD-MON-YY'), 'buy', 50, 10, 500);
INSERT INTO TRXLOG
VALUES (DEFAULT, 'mike', 'MM', TO_DATE('01-APR-20', 'DD-MON-YY'), 'sell', 50, 15, 750);

--INSERT VALUES INTO THE ALLOCATION TABLE
INSERT INTO ALLOCATION
VALUES (0, 'mike', TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO ALLOCATION
VALUES (1, 'mary', TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO ALLOCATION
VALUES (2, 'mike', TO_DATE('03-MAR-20', 'DD-MON-YY'));

--INSERT VALUES INTO THE PREFERS TABLE
INSERT INTO PREFERS
VALUES (0, 'MM', .5);
INSERT INTO PREFERS
VALUES (0, 'RE', .5);
INSERT INTO PREFERS
VALUES (1, 'STB', .2);
INSERT INTO PREFERS
VALUES (1, 'LTB', .4);
INSERT INTO PREFERS
VALUES (1, 'BBS', .4);
INSERT INTO PREFERS
VALUES (2, 'GS', .3);
INSERT INTO PREFERS
VALUES (2, 'AS', .3);
INSERT INTO PREFERS
VALUES (2, 'IMS', .4);

--INSERT INTO THE CLOSING PRICE TABLE
INSERT INTO CLOSING_PRICE
VALUES ('MM', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('MM', 11, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('MM', 12, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('MM', 15, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('MM', 14, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('MM', 15, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('MM', 16, TO_DATE('03-APR-20', 'DD-MON-YY'));

INSERT INTO CLOSING_PRICE
VALUES ('RE', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('RE', 12, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('RE', 15, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('RE', 14, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('RE', 16, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('RE', 17, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('RE', 15, TO_DATE('03-APR-20', 'DD-MON-YY'));

INSERT INTO CLOSING_PRICE
VALUES ('STB', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('STB', 9, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('STB', 10, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('STB', 12, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('STB', 14, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('STB', 10, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('STB', 12, TO_DATE('03-APR-20', 'DD-MON-YY'));

INSERT INTO CLOSING_PRICE
VALUES ('LTB', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('LTB', 12, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('LTB', 13, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('LTB', 15, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('LTB', 12, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('LTB', 9, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('LTB', 10, TO_DATE('03-APR-20', 'DD-MON-YY'));

INSERT INTO CLOSING_PRICE
VALUES ('BBS', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('BBS', 11, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('BBS', 14, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('BBS', 18, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('BBS', 13, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('BBS', 15, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('BBS', 16, TO_DATE('03-APR-20', 'DD-MON-YY'));

INSERT INTO CLOSING_PRICE
VALUES ('SRBS', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('SRBS', 12, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('SRBS', 12, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('SRBS', 14, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('SRBS', 17, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('SRBS', 20, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('SRBS', 20, TO_DATE('03-APR-20', 'DD-MON-YY'));

INSERT INTO CLOSING_PRICE
VALUES ('GS', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('GS', 12, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('GS', 13, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('GS', 15, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('GS', 14, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('GS', 15, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('GS', 12, TO_DATE('03-APR-20', 'DD-MON-YY'));

INSERT INTO CLOSING_PRICE
VALUES ('AS', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('AS', 15, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('AS', 14, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('AS', 16, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('AS', 14, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('AS', 17, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('AS', 18, TO_DATE('03-APR-20', 'DD-MON-YY'));

INSERT INTO CLOSING_PRICE
VALUES ('IMS', 10, TO_DATE('28-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('IMS', 12, TO_DATE('29-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('IMS', 12, TO_DATE('30-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('IMS', 14, TO_DATE('31-MAR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('IMS', 13, TO_DATE('01-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('IMS', 12, TO_DATE('02-APR-20', 'DD-MON-YY'));
INSERT INTO CLOSING_PRICE
VALUES ('IMS', 11, TO_DATE('03-APR-20', 'DD-MON-YY'));
